#!/bin/bash

HELPER_DIR="/usr/local/share/grmr"

usage() {
	echo -e "grmr - Simple grammary and style checker.\n"
	echo -e "Usage:"
	echo -e "  grmr file1.tex file2.txt ..."
	echo -e "  grmr [command] file1.tex file2.tex ..."
	echo -e ""
	echo -e "Available Commands:"

	echo -n "  help"
	echo -e "\t\t\tPrints the usage"

	echo -n "  weasel file1.tex file2.txt ..."
	echo -e "\t\t\tCheck documents only for weasel words. Weasel words make sentence 'weaker'."

	echo -n "  passive file1.tex file2.txt ..."
	echo -e "\t\t\tCheck documents only for passive voice. Using passive voice can hide important informations"

	echo -n "  ill file1.tex file2.txt ..."
	echo -e "\t\t\tCheck documents only for illusion/duplicate words like: \"... the the ...\" etc."
	echo -e ""
}

grmr_check_weasel() {
	echo "weasel words: "
	sh "$HELPER_DIR/weasel.sh" $*
	echo ""
}

grmr_check_passive() {
	echo "passive voice: "
	sh "$HELPER_DIR/passive.sh" $*
	echo ""
}

grmr_check_ill() {
	echo "duplicates: "
	perl "$HELPER_DIR/ill" $*
	echo ""
}

grmr_check() {
	grmr_check_weasel $*
	grmr_check_passive $*
	grmr_check_ill $*
}

case "$#:$1" in
	0:*|1:help|1:passive|1:weasel|1:ill)
		usage
		;;
	*:weasel)
		shift 1
		grmr_check_weasel $*
		;;
	*:passive)
		shift 1
		grmr_check_passive $*
		;;
	*:ill)
		shift 1
		grmr_check_ill $*
		;;
	*)
		grmr_check $*
		;;
esac
